layout_spectrum: 0.33311807410791516
typography_spectrum: 0.21205329545773566
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.378246933221817
  lightness: 0.6329212496057153
  saturation: 0.6392369491513819
  rhythmicContrast: 0.6073294465895742
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Colours  Foto
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Colour's ® Foto
purpose: []
