typography_spectrum: 0.42616
color:
  brandColors:
    - '#92808c'
    - '#baa9af'
    - '#edcfd1'
    - '#010000'
    - '#7e3e25'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.0802016737870872
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99812
analytics:
  google: null
  facebook: null
  twitter: null
name: Colours  Foto
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Colour's ® Foto
purpose: []
